import { Home } from 'lucide-react'
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Coffee | Login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className='grid grid-cols-2 px-5 py-10 gap-10 h-[calc(100vh-74px)]'>
      <div className='hidden lg:flex flex-col border border-border rounded-xl p-8'>
        <div className='flex-1 flex flex-col'>
          <Link href={'/'} className='hover:underline self-start'>
            <h1 className='flex items-center gap-1'>
              <Home size={18} />
              Home
            </h1>
          </Link>
        </div>

        <footer>@2021 Coffee</footer>
      </div>

      {children}
    </main>
  )
}
