export const products = [
  {
    id: '1',
    name: 'Expresso Tradicional',
    categories: ['tradicional'],
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '2',
    name: 'Expresso Americano',
    categories: ['tradicional'],
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '3',
    name: 'Expresso Cremoso',
    categories: ['tradicional'],
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '4',
    name: 'Expresso Gelado',
    categories: ['tradicional', 'gelado'],
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '5',
    name: 'Café com Leite',
    categories: ['tradicional', 'com leite'],
    description: 'Meio a meio de expresso tradicional com leite vaporizado',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '6',
    name: 'Latte',
    categories: ['tradicional', 'com leite'],
    description:
      'Uma dose de café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '7',
    name: 'Capuccino',
    categories: ['tradicional', 'com leite'],
    description:
      'Bebida com canela feita de doses iguais de café, leite e espuma',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '8',
    name: 'Macchiato',
    categories: ['tradicional', 'com leite'],
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '9',
    name: 'Mocaccino',
    categories: ['tradicional', 'com leite'],
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '10',
    name: 'Chocolate Quente',
    categories: ['especial', 'com leite'],
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '11',
    name: 'Cubano',
    categories: ['especial', 'alcoólico', 'gelado'],
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '12',
    name: 'Havaiano',
    categories: ['especial'],
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '13',
    name: 'Árabe',
    categories: ['especial'],
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    image: '/coffee-product.svg',
  },
  {
    id: '14',
    name: 'Irlandês',
    categories: ['especial', 'alcoólico'],
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    image: '/coffee-product.svg',
  },
]
