import type { Metadata } from 'next'
import { Prompt } from 'next/font/google'
import './globals.css'
import { Header } from './_components/app/header'

const prompt = Prompt({
  weight: ['300', '400', '500', '600', '700'],
  subsets: ['latin-ext'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Coffee | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='pt-BR'>
      <body className={prompt.className}>
        <Header />
        {children}
      </body>
    </html>
  )
}
